name: multicam-gt
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - embree=2.17.7
  - icu=73.2
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libhwloc=2.11.1
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libpq=12.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=1.41.5
  - libxml2=2.13.1
  - ncurses=6.4
  - numpy=1.26.4
  - openssl=3.3.2
  - pip=24.2
  - postgresql=12.20
  - python=3.11.10
  - python_abi=3.11
  - readline=8.2
  - sqlite=3.45.3
  - tbb=2021.13.0
  - tk=8.6.14
  - tzdata=2024b
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.2
      - asgiref==3.8.1
      - asttokens==2.4.1
      - astunparse==1.6.3
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - coloredlogs==15.0.1
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==0.29.37
      - debugpy==1.8.14
      - decorator==5.1.1
      - django==4.1.7
      - django-bootstrap-form==3.4
      - dlib==19.24.9
      - executing==2.1.0
      - facenet-pytorch==2.6.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fonttools==4.54.1
      - fsspec==2025.5.1
      - gast==0.6.0
      - gdown==5.2.0
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - h5py==3.12.1
      - humanfriendly==10.0
      - idna==3.10
      - ipdb==0.13.13
      - ipykernel==6.29.5
      - ipython==8.29.0
      - jedi==0.19.1
      - jinja2==3.1.6
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - namex==0.0.9
      - narwhals==1.45.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.20.1
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.15.0
      - packaging==24.1
      - pandas==1.5.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - prompt-toolkit==3.0.48
      - protobuf==5.28.3
      - psutil==7.0.0
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyembree==0.1.12
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyzmq==27.0.0
      - referencing==0.36.2
      - requests==2.32.3
      - retina-face==0.0.17
      - rich==14.0.0
      - rpds-py==0.26.0
      - rtmlib==0.0.13
      - rtree==1.3.0
      - scipy==1.14.1
      - setuptools==60.10.0
      - shapely==2.0.6
      - six==1.16.0
      - soupsieve==2.7
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - torch==2.6.0+cpu
      - torchaudio==2.6.0+cpu
      - torchvision==0.21.0+cpu
      - tornado==6.5.1
      - tqdm==4.66.6
      - traitlets==5.14.3
      - trimesh==3.23.5
      - triton==2.2.0
      - typing-extensions==4.12.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wheel==0.37.1
      - wrapt==1.17.2
