# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pom_file', models.CharField(max_length=30)),
                ('frame_number', models.PositiveIntegerField(default=0)),
                ('rectangleID', models.PositiveIntegerField(default=0)),
                ('personID', models.PositiveSmallIntegerField(default=0)),
                ('modified_flag', models.BooleanField(default=False)),
                ('coordinates', models.CommaSeparatedIntegerField(max_length=180)),
            ],
        ),
    ]
