# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='coordinates',
            field=models.CharField(max_length=180, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
