# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0003_rectanges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rectanges',
            new_name='Rectangles',
        ),
    ]
