# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0005_auto_20161018_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectangle',
            name='xMid',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
