# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0006_rectangle_xmid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='pom_file',
        ),
    ]
