# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marker', '0009_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
