# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerID', models.PositiveIntegerField(default=0)),
                ('frameNB', models.PositiveSmallIntegerField(default=0)),
                ('validationoCode', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('state', models.IntegerField(default=-1)),
            ],
        ),
    ]
