# Generated by Django 4.1.7 on 2023-03-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gtm_hit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.IntegerField(verbose_name="PersonID"),
        ),
    ]
