# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='validationoCode',
            new_name='validationCode',
        ),
        migrations.AddField(
            model_name='worker',
            name='tuto',
            field=models.BooleanField(default=False),
        ),
    ]
