# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0003_auto_20161108_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='frame_labeled',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='frameNB',
            field=models.IntegerField(default=-1),
        ),
    ]
