# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0005_auto_20161110_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationcode',
            name='validationCode',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
