# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0006_auto_20161110_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationcode',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gtm_hit.Worker', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationcode',
            name='workerID',
            field=models.TextField(max_length=40, unique=True),
        ),
    ]
