# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0007_auto_20161110_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationcode',
            name='worker',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gtm_hit.Worker'),
        ),
    ]
