# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtm_hit', '0010_worker_time_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='time_list',
            field=models.TextField(default=''),
        ),
    ]
